### ISSUE TITLE
Basic project documentation

### ISSUE THREAD

**Issue by klokan** [moravianlibrary/imagesearch.mzk.cz#1]
Rewrite the README.md - something a la https://github.com/klokantech/tileserver-php/.

Provide Usage, Screenshot, Installation, API, section, ...
Later we have to add the links to the published articles as well.

**Comment by klokan** [comment]
Update LIRE readme.
Create new readme for the new branch.

**Comment by dudaerich** [comment]
LIRE readme updated https://github.com/moravianlibrary/imagesearch.mzk.cz/tree/lire

**Comment by dudaerich** [comment]
https://github.com/moravianlibrary/imagesearch.mzk.cz/blob/master/README.md
