### ISSUE TITLE
FastCGI search service in a docker image

### ISSUE THREAD

**Issue by klokan** [moravianlibrary/imagesearch.mzk.cz#10]
Implementing the fast search with hamming distance in C.

Search should support both BlockHash and DHash.

The docker should contain also the two indexers (DHash #11 and Blockhash) - command line.

This should solve basic search primarily (with a hash/hashes or image) as a parameter.

Ingesting API should be discussed and developed separately - #4

**Comment by dudaerich** [comment]
Bruteforce implementation https://gist.github.com/dudaerich/93203d08e1ba712fa4af

**Comment by klokan** [comment]
@dudaerich could you please prioritise this?

**Comment by dudaerich** [comment]
Yes of course.

**Comment by dudaerich** [comment]
Do you agree with my suggestion to implement the service in Python? The suggestion is made based on this investigation https://github.com/moravianlibrary/imagesearch.mzk.cz/issues/11#issuecomment-102059982

**Comment by klokan** [comment]
I am afraid the search system for hamming distance itself should be made in C/C++ - otherwise it will have bad performance.

The time to calculate the hash of query image is small and done just once and does not matter that much. Important is how do you index the hashes for all images and how you find the similar one in such a database. 

Here is your note from #6 which got lost:

> The developers of pHash library releases implementation of MVP tree as standalone data structure.  See http://www.phash.org/download/ The implementation allows to store and retrieve records based on hamming distance. It should be compared with brute force technique.

The questions are:
- What is the status of comparing the MVP tree with brutal force search?
- What do you plan to use as the core for the search system?

In general - I am not against python for ingest API or hash calculation during ingest or before search, or as a glue for FastCGI - but usually it is VERY BAD at low level data indexing and search when it comes to speed. 

The search system itself should get the hashes and give your ID of images. This must be fastest possible...

**Comment by dudaerich** [comment]
Ok, I agree.

I didn't compare MVP tree with brutal force yet.
I plan to use MVP tree as the core for the search system.

The implementation will be done in C/C++.

**Comment by dudaerich** [comment]
I made several tests targeting on data structures, which enable find record with the smallest hamming distance.

Candidates:
- std::vector and brute force
- mvptree
- sqlite and brute force

Tests were done on 45 294 indexed images.
Query set contains 3826 images.

Results:

| Data structure | Time | Average time for one image |
| --- | --- | --- |
| std::vector | 14s | 0.0037s |
| mvptree | 25s | 0.0065s |
| sqlite | 58s | 0.0152s |

MVPTree returns for pair (hash, radius) all records that have smaller distance than given radius. Smaller radius means faster searching. Tests were done with radius 2.0. When I tried radius 1.5, the speed was the same as in case of std::vector, but the program didn't find all records. However when the data will be grown up, the MVPTree may be faster (I don't know).

Advantage of std::vector is that we can in one traversal find the smallest hamming distance for both blockhash and dhash.

@klokan what do you think about it?

**Comment by klokan** [comment]
Can you estimate (or test on artificially generated dataset) speed and **memory requirements** for the mentioned alternative if there would be for example 2 millions records? Will it still easily fit into RAM for std::vector?

We need to have both in memory (blockhash + dhash) - how much memory is required? 

I guess (and hope) MVPTree would perform better on such a dataset - if it skips some records.

Please run some tests on 2 million records and let me know something about memory requirements of the brute force approach - before we can make a decision.

**Comment by dudaerich** [comment]
Query set contains 3826 hashes.
Index contains 2 000 000 hashes.

| Data structure | Time | Memory | Average time for one image |
| --- | --- | --- | --- |
| std::vector | 9m3.477s | 200 MB | 0.142s |
| mvptree | 37m46.314s | 361 MB | 0.592s |

Procedure that generates hashes

``` c
#include <iostream>
#include <iomanip>
#include <stdint.h>

#define COUNT 2000000

using namespace std;
int main(int argc, char **argv) {
    const uint64_t step = ((uint64_t) -1) / COUNT;
    uint64_t n;
    uint64_t i;

    for (n = 0, i = 0; i < COUNT; i++, n += step) {
        cout << setfill('0') << setw(16) << hex << n << " file" << i << endl;
    }

    return 0;
}
```

Both blockhash and dhash generates hash of length 64 bits so one hash takes 8B. Consider that identifier won't be bigger than 64B then one record takes 2*8B + 64B = 80B
2 million records requires 2 000 000 \* 80B = 160000000B = 152,6 MB

**Comment by dudaerich** [comment]
Above implementation of mvptree was compiled with -g3 option. I tried to compile it with -O3 option but results were still worse than in std::vector. The time was 25m11.907s.

Notice: std::vector in above test was compiled with -O3 option.

**Comment by klokan** [comment]
Go for std::vector.

**Comment by klokan** [comment]
What is the status on this?

**Comment by dudaerich** [comment]
Implementation is done. I need to know which metadata the service should contain and then upload data to it.

**Comment by klokan** [comment]
URLs? Where is the source - what is the docker image on hub?

**Comment by dudaerich** [comment]
I will upload it for a moment.

**Comment by klokan** [comment]
Metadata = MapID from the Georeferencer of the StareMapy.cz - available in the Fusion Tables. Indexing all maps from StareMapy.cz.

"2kkkepIJCPtJnogMl4NDB6" from  http://staremapy.georeferencer.cz/map/2kkkepIJCPtJnogMl4NDB6/201507231053-7YiH4K/visualize
and possibly:
"mzk/2619267604" from http://staremapy.georeferencer.cz/api/external/mzk/2619267604
for thumbnail:
http://lh5.ggpht.com/47_QJVprvteipe4wZQ98Nl6BzyWnuzPfLKqXFWB0aw9f4jllfJHhOmzdPTRU_k8Cqfrwf-CvBYM19MXGk9nslyc21-U

**Comment by dudaerich** [comment]
Source code is uploaded on github, Dockerhub I will set tomorrow, because due to some weird error I cannot create new automated builds based on projects from moravianlibrary github.

**Comment by dudaerich** [comment]
https://registry.hub.docker.com/u/moravianlibrary/imagesearch.mzk.cz/

**Comment by klokan** [comment]
+1 Looks great! Will test it soon.

**Comment by dudaerich** [comment]
The running instance filled with data from [StareMapy.cz](http://www.staremapy.cz/) you can find on url http://imagesearch.mzk.cz/

**Comment by klokan** [comment]
Cool! Could you please add the identifers of the maps - with links to www.staremapy.cz? Otherwise you just find an image but you have no clue which map was it..

**Comment by dudaerich** [comment]
Done
