### ISSUE TITLE
Autogeoreference web service in a docker

### ISSUE THREAD

**Issue by klokan** [moravianlibrary/imagesearch.mzk.cz#13]
Web service in a docker.
Receives two identifiers of images (source, target) where for source also existing georeference.

It calculates new set of GCPs for target and submits the form to create new georeference on Georeferencer.

**Comment by dudaerich** [comment]
Data needed for autogeoreferencing will be downloaded from Georeferencer API or should be provided by a client?

**Comment by klokan** [comment]
Downloaded from Georeferencer API - by this service.

You pass only the identifers.

**Comment by dudaerich** [comment]
What about image data? The analyze must be done on images with high resolution. Probably the only way how to do it is to tag together image from tiles.

My question is: Which "zoomify" protocols are supported by georeferencer?

**Comment by dudaerich** [comment]
https://github.com/moravianlibrary/autogeoreference
https://hub.docker.com/r/moravianlibrary/autogeoreference/
