### ISSUE TITLE
Docker for imagesearch

### ISSUE THREAD

**Issue by klokan** [moravianlibrary/imagesearch.mzk.cz#2]
The whole service should be directly usable with Docker container.

It will have the 'latest' tag for production version, and 'devel' tag for development.

It will have inside only the Java servlets - it is expected the requests are forwarded from Apache outside to docker.

Provide at least basic README.md in folder with Dockerfile - to have description on docker hub.

Docker should be auto built on Docker Hub - based on GitHub. 

Final location:
https://registry.hub.docker.com/u/moravianlibrary/imagesearch/

**Comment by dudaerich** [comment]
https://registry.hub.docker.com/u/moravianlibrary/imagesearch.mzk.cz/
