### ISSUE TITLE
API implementation

### ISSUE THREAD

**Issue by klokan** [moravianlibrary/imagesearch.mzk.cz#4]
As discussed in the email - endpoints for:

Public:
/search?url=http://server/image.jpeg
/search - via upload HTTP POST
/search?dhash=asdfasdfasf
/search?blockhash=asdfasdfas
/search?dhash=asdfasdf&blockhash=asdfasdfads

Private (used behind Apache .htaccess with password):
/ingest
/reindex

**Comment by klokan** [comment]
Ingest to be discussed.

**Comment by klokan** [comment]
Ingest process for a similar project is now being developed at https://github.com/klokantech/hawk, see https://github.com/klokantech/hawk/wiki/C.Ingest.
It is an open-source project made in Python, with Redis as backend for key-value store and for tasks in queues. Can be reused for the ingesting here when finished (about a month time).

**Comment by dudaerich** [comment]
What types of metadata the ImageSearch should store for maps?

I suggest:

| Name | Description |
| --- | --- |
| Id | georeferencer id |
| Title |  |
| NumGcps | number of geoereferenced points |
| RmsError | statistical error |
| thumbnail_url | url to the thumbnail |
| control_points | georeferenced points |
| cutline |  |
| url | url to original map |

Something else?

**Comment by dudaerich** [comment]
See README of project.

**Comment by dudaerich** [comment]
The metadata property was added, which can contain arbitrary JSON value.
