### ISSUE TITLE
SIFT as alternative to SURF

### ISSUE THREAD

**Issue by klokan** [moravianlibrary/imagesearch.mzk.cz#7]
Compare performance on SIFT vs existing implementation of SURF for feature detection.

**Comment by klokan** [comment]
This was related to LIRE. Maybe test on OpenCV.

**Comment by dudaerich** [comment]
GDAL-correlator uses modified SURF algorithm together with some heuristics for finding identical points on two similar images. I tried it for searching identical points on two historical maps and the results were very good (much better than basic SIFT or SURF).
