### ISSUE TITLE
Auto georeference 

### ISSUE THREAD

**Issue by klokan** [moravianlibrary/imagesearch.mzk.cz#8]
OpenCV:
http://docs.opencv.org/

Explore FLANN library for matching two sets for features detected by SIFT / SURF:
https://github.com/mariusmuja/flann

and the same in OpenCV:
http://docs.opencv.org/modules/features2d/doc/common_interfaces_of_descriptor_matchers.html?highlight=flannbasedmatcher#flannbasedmatcher

GDAL Correlator: https://github.com/migal-drew/GDAL-correlator

**Comment by klokan** [comment]
Make a fork of migal-drew/GDAL-correlator please - and add Makefile and properly test.

Calculate affine transformation between raster coordinates of two maps (Least Square Method):
https://code.google.com/p/oldmapsonline/source/browse/trunk/gcps2wld/python-no-dep/gcps2wld.py#94

Apply the affine tranformation to raster coordinates of existing set of GCPs on source map and create new GCPs for the target map with equal lat/lon coordinates, but new raster coordinates.

Deliverable is a library here. Web service is in a separate ticket #13.

Try it on thumbnails - and report if this is enough. I expect the high-res images in native resolutions are required.

**Comment by dudaerich** [comment]
GDAL-correlator is better for finding pairs on two maps than using basic SIFT or SURF. However there can arise errors that could cause problems to Least Square Method.

![out](https://cloud.githubusercontent.com/assets/2317374/7272695/3f920ad0-e8ed-11e4-8e04-32f298bc9ceb.jpg)

I suggest to use [RANSAC](http://en.wikipedia.org/wiki/RANSAC) algorithm that can exclude outliers from data model. There is also an [implementation in OpenCV](http://docs.opencv.org/doc/tutorials/features2d/feature_homography/feature_homography.html).

**Comment by dudaerich** [comment]
I tried to use GDAL-correlator for finding pairs on two maps. Then I computed the affine transformation matrix using this code http://www.programdevelop.com/3975975/ and the result looks very good :) See images. I selected one point and then I applied transformation matrix on it.

![map1](https://cloud.githubusercontent.com/assets/2317374/8852734/395d9db6-3157-11e5-8574-18bf3cf1ba4a.jpg)
![map2](https://cloud.githubusercontent.com/assets/2317374/8852736/3b3d5ea0-3157-11e5-9de3-a05be240a171.jpg)

**Comment by dudaerich** [comment]
https://github.com/moravianlibrary/autogeoreference
